'use client';
import { useCallback, useEffect, useState } from 'react';
import ImageUpload from './image-upload';
import { signOut } from 'next-auth/react';
import { ArrowUpRight, Plus, Save, LogOut, Trash2 } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { contentSchema,type SavedContent,type SiteContent } from '@/lib/content-schema';

function Field({label,value,onChange,multiline=false,type='text',hint}:{label:string;value:string;onChange:(value:string)=>void;multiline?:boolean;type?:string;hint?:string}) {
  return <label className="admin-field"><span>{label}</span>{multiline ? <Textarea value={value} rows={4} onChange={event=>onChange(event.target.value)}/> : <Input type={type} value={value} onChange={event=>onChange(event.target.value)}/ >}{hint && <small>{hint}</small>}</label>;
}

export default function Editor({initial,email}:{initial:SavedContent;email:string}) {
  const [saved,setSaved] = useState(initial);
  const [draft,setDraft] = useState<SiteContent>(initial.content);
  const [busy,setBusy] = useState(false);
  const [uploadCount,setUploadCount] = useState(0);
  const onUploadBusy = useCallback((active:boolean)=>setUploadCount(count=>Math.max(0,count+(active ? 1 : -1))),[]);
  const locked=busy || uploadCount>0;
  const [message,setMessage] = useState('');
  const [failure,setFailure] = useState(false);
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved.content);
  useEffect(()=>{
    const warn = (event:BeforeUnloadEvent) => { if(dirty || uploadCount>0) {event.preventDefault();event.returnValue='';} };
    window.addEventListener('beforeunload',warn);return ()=>window.removeEventListener('beforeunload',warn);
  },[dirty,uploadCount]);
  const edit = (change:(next:SiteContent)=>void) => {setDraft(previous=>{const next=structuredClone(previous);change(next);return next;});setMessage('');};
  async function save() {
    const valid = contentSchema.safeParse(draft);
    if(!valid.success) {setFailure(true);setMessage(valid.error.issues.map(issue=>`${issue.path.join('.')}: ${issue.message}`).slice(0,3).join(' '));return;}
    setBusy(true);setMessage('');
    try {
      const response = await fetch('/api/admin/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:saved.revision,content:valid.data})});
      const result = await response.json();
      if(!response.ok) throw new Error(result.error || 'Unable to save. Please try again.');
      setSaved(result);setDraft(result.content);setFailure(false);setMessage('Saved. Your changes are now visible on the website.');
    } catch(error) {setFailure(true);setMessage(error instanceof Error ? error.message : 'Unable to save. Your edits are still here.');}
    finally{setBusy(false);}
  }
  return <>
    <header className="admin-header"><a href="/" target="_blank" rel="noreferrer" className="admin-brand">UB <span>ENTERTAINMENT / ADMIN</span></a><div><a href="/" target="_blank" rel="noreferrer">View website <ArrowUpRight size={16}/></a><Button variant="outline" disabled={dirty || locked} title={dirty ? 'Save or discard your edits before signing out.' : 'Sign out'} onClick={()=>signOut({callbackUrl:'/admin/login'})}><LogOut size={16}/>Sign out</Button></div></header>
    <main className="admin-main"><div className="admin-heading"><div><p className="eyebrow">Your studio, in focus</p><h1>Website content.</h1><p>Signed in as {email}</p></div><div className="admin-save"><span>{dirty ? 'Unsaved changes' : saved.updatedAt ? `Saved ${new Date(saved.updatedAt).toLocaleString('en-IN')}` : 'Ready to edit'}</span><Button onClick={save} disabled={!dirty || locked}><Save size={17}/>{busy ? 'Saving…' : 'Save changes'}</Button></div></div>
    {message && <p className={failure ? 'admin-alert' : 'admin-success'} role={failure ? 'alert' : 'status'}>{message}</p>}
    {dirty && <div className="draft-notice">Changes stay in your draft until you save.<Button variant="ghost" disabled={locked} onClick={()=>{setDraft(structuredClone(saved.content));setMessage('Draft discarded.');setFailure(false);}}>Discard unsaved edits</Button></div>}
    <fieldset disabled={locked} className="admin-fields"><legend className="sr-only">Edit website content</legend><Tabs defaultValue="studio" className="admin-tabs"><TabsList variant="line" aria-label="Content sections"><TabsTrigger value="studio">Studio</TabsTrigger><TabsTrigger value="services">Services</TabsTrigger><TabsTrigger value="gallery">Gallery</TabsTrigger><TabsTrigger value="news">News & events</TabsTrigger><TabsTrigger value="contact">Contact</TabsTrigger></TabsList>
      <TabsContent value="studio"><section className="editor-section"><div className="editor-intro"><h2>The opening frame.</h2><p>Update your headline, introduction, and hero image.</p></div><div className="editor-card"><div className="field-grid three"><Field label="Headline — first line" value={draft.hero.line1} onChange={value=>edit(next=>{next.hero.line1=value;})}/><Field label="Headline — second line" value={draft.hero.line2} onChange={value=>edit(next=>{next.hero.line2=value;})}/><Field label="Gold accent text" value={draft.hero.accent} onChange={value=>edit(next=>{next.hero.accent=value;})}/></div><Field label="Hero introduction" multiline value={draft.hero.subtitle} onChange={value=>edit(next=>{next.hero.subtitle=value;})}/><div className="field-grid"><ImageUpload label="Hero image" onBusyChange={onUploadBusy} value={draft.hero.image} onChange={value=>edit(next=>{next.hero.image=value;})}/><Field label="Image description" value={draft.hero.imageAlt} onChange={value=>edit(next=>{next.hero.imageAlt=value;})}/></div><Field label="Image caption / credit note" value={draft.hero.imageNote} onChange={value=>edit(next=>{next.hero.imageNote=value;})}/></div><div className="editor-intro"><h2>About the studio.</h2></div><div className="editor-card"><Field label="Opening statement" multiline value={draft.about.lead} onChange={value=>edit(next=>{next.about.lead=value;})}/><Field label="About UB Entertainment" multiline value={draft.about.body} onChange={value=>edit(next=>{next.about.body=value;})}/><div className="field-grid"><ImageUpload label="Founder / Studio image" onBusyChange={onUploadBusy} value={draft.about.image ?? '/assets/ukbath.jpg'} onChange={value=>edit(next=>{next.about.image=value;})}/><Field label="Founder name" value={draft.about.founder ?? 'Ukbath'} onChange={value=>edit(next=>{next.about.founder=value;})}/></div></div></section></TabsContent>
      <TabsContent value="services"><section className="editor-section"><div className="editor-intro"><h2>What you create.</h2><p>Edit the three production services shown on the website.</p></div>{draft.services.map((item,index)=><div className="editor-card" key={item.id}><h3>{String(index+1).padStart(2,'0')} / {item.title}</h3><div className="field-grid"><Field label="Service name" value={item.title} onChange={value=>edit(next=>{next.services[index].title=value;})}/><Field label="Keywords" value={item.tags} onChange={value=>edit(next=>{next.services[index].tags=value;})}/></div><Field label="Description" multiline value={item.description} onChange={value=>edit(next=>{next.services[index].description=value;})}/><div className="field-grid"><ImageUpload label="Image" onBusyChange={onUploadBusy} value={item.image} onChange={value=>edit(next=>{next.services[index].image=value;})}/><Field label="Image description" value={item.alt} onChange={value=>edit(next=>{next.services[index].alt=value;})}/></div></div>)}</section></TabsContent>
      <TabsContent value="gallery"><section className="editor-section"><div className="editor-intro"><h2>Your visual world.</h2><p>The first image gets the largest space. Add project stills and update the representative-imagery note when ready.</p></div><div className="editor-card"><Field label="Gallery introduction" value={draft.gallery.description} onChange={value=>edit(next=>{next.gallery.description=value;})}/><Field label="Gallery note" value={draft.gallery.note} onChange={value=>edit(next=>{next.gallery.note=value;})}/></div>{draft.gallery.items.map((item,index)=><div className="editor-card" key={item.id}><div className="item-heading"><h3>Image {index+1}</h3><Button variant="outline" onClick={()=>edit(next=>{next.gallery.items.splice(index,1);})}><Trash2 size={16}/>Remove from draft</Button></div><div className="field-grid"><Field label="Title" value={item.title} onChange={value=>edit(next=>{next.gallery.items[index].title=value;})}/><Field label="Category" value={item.category} onChange={value=>edit(next=>{next.gallery.items[index].category=value;})}/><ImageUpload label="Image" onBusyChange={onUploadBusy} value={item.image} onChange={value=>edit(next=>{next.gallery.items[index].image=value;})}/><Field label="Image description" value={item.alt} onChange={value=>edit(next=>{next.gallery.items[index].alt=value;})}/></div></div>)}{draft.gallery.items.length===0 && <p className="editor-empty">No gallery images yet. Add your first image below.</p>}<Button variant="outline" disabled={draft.gallery.items.length>=30} onClick={()=>edit(next=>{next.gallery.items.push({id:crypto.randomUUID(),title:'New project',category:'PROJECT STILL',image:'/assets/hero.jpg',alt:'Describe the project image'});})}><Plus size={16}/>Add gallery image</Button></section></TabsContent>
      <TabsContent value="news"><section className="editor-section"><div className="editor-intro"><h2>The next chapter.</h2><p>Add announcements and events. New items appear first.</p><Button variant="outline" disabled={draft.news.length>=30} onClick={()=>edit(next=>{next.news.unshift({id:crypto.randomUUID(),title:'New announcement',category:'STUDIO NEWS',date:new Date().toISOString().slice(0,10),image:'/assets/ub-logo.png',body:'Write your announcement before saving.'});})}><Plus size={16}/>Add announcement</Button></div>{draft.news.map((item,index)=><div className="editor-card" key={item.id}><div className="item-heading"><h3>Announcement {index+1}</h3><Button variant="outline" onClick={()=>edit(next=>{next.news.splice(index,1);})}><Trash2 size={16}/>Remove from draft</Button></div><Field label="Headline" value={item.title} onChange={value=>edit(next=>{next.news[index].title=value;})}/><div className="field-grid"><Field label="Category" value={item.category} onChange={value=>edit(next=>{next.news[index].category=value;})}/><Field label="Date" hint="Use YYYY-MM-DD, or a year such as 2026." value={item.date} onChange={value=>edit(next=>{next.news[index].date=value;})}/></div><ImageUpload label="Image" onBusyChange={onUploadBusy} value={item.image} onChange={value=>edit(next=>{next.news[index].image=value;})}/><Field label="Announcement" multiline value={item.body} onChange={value=>edit(next=>{next.news[index].body=value;})}/></div>)}{draft.news.length===0 && <p className="editor-empty">No announcements yet. The website will show its coming-soon message.</p>}</section></TabsContent>
      <TabsContent value="contact"><section className="editor-section"><div className="editor-intro"><h2>Keep the conversation going.</h2><p>These details are public. Leave fields blank to hide them.</p></div><div className="editor-card"><Field label="Location" value={draft.contact.location} onChange={value=>edit(next=>{next.contact.location=value;})}/><div className="field-grid"><Field label="Public email address" type="email" value={draft.contact.email} onChange={value=>edit(next=>{next.contact.email=value;})}/><Field label="Phone number" type="tel" value={draft.contact.phone} onChange={value=>edit(next=>{next.contact.phone=value;})}/><Field label="WhatsApp number" type="tel" hint="e.g. +91 98765 43210. Enables direct WhatsApp chat links and the floating chat button." value={draft.contact.whatsapp ?? ''} onChange={value=>edit(next=>{next.contact.whatsapp=value;})}/><Field label="Instagram profile URL" type="url" value={draft.contact.instagram} onChange={value=>edit(next=>{next.contact.instagram=value;})}/><Field label="YouTube channel URL" type="url" value={draft.contact.youtube} onChange={value=>edit(next=>{next.contact.youtube=value;})}/></div></div></section></TabsContent>
    </Tabs></fieldset></main><footer className="admin-footer">UB ENTERTAINMENT <span>Local content management · Protected admin session</span></footer>
  </>;
}

